version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - app-tier
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    platform: linux/amd64 # Specify the target platform here
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - app-tier
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  backend:
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    env_file:
      - .env
    environment:
      - ELASTIC_NODE=http://host.docker.internal:9200
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - '8080'
    ports:
      - '8080:8080'
    networks:
      - app-tier

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   expose:
  #     - '3306'
  #   ports:
  #     - '3306:3306'
  #   # networks:
  #   #   - app-tier
  #   environment:
  #     MYSQL_DATABASE: aliconcon
  #     MYSQL_ALLOW_EMPTY_PASSWORD: yes
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: dbuser
  #     MYSQL_ROOT_HOST: '%'
